# Generated by Django 4.2.4 on 2023-10-06 11:44

from django.db import migrations, models
import innova.models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=innova.models.upload_logo),
        ),
    ]
