# Generated by Django 4.2.4 on 2023-10-06 13:07

from django.db import migrations, models
import innova.models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0002_partner_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('Last_update_date', models.DateTimeField(auto_now=True)),
                ('Last_update_by', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Image', models.ImageField(upload_to=innova.models.upload_image)),
                ('order_by', models.IntegerField()),
                ('active_flag', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='media',
            old_name='order',
            new_name='order_by',
        ),
    ]
