# Generated by Django 4.2.4 on 2023-10-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0004_productcategory_therapeuticareas_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
    ]
