# Generated by Django 4.2.4 on 2023-10-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0005_products_active_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='order_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
