# Generated by Django 4.2.4 on 2023-10-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0006_products_order_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinformation',
            name='Image',
        ),
    ]
