# Generated by Django 4.2.4 on 2023-12-16 04:51

from django.db import migrations, models
import innova.models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0011_alter_career_address_alter_career_jobvacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='Image',
            field=models.ImageField(null=True, upload_to=innova.models.upload_image),
        ),
    ]
