# Generated by Django 4.2.4 on 2023-12-18 14:03

from django.db import migrations, models
import django.db.models.deletion
import innova.models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0012_companyinformation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('Last_update_date', models.DateTimeField(auto_now=True)),
                ('Last_update_by', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Image', models.ImageField(null=True, upload_to=innova.models.upload_image)),
                ('order_by', models.IntegerField()),
                ('active_flag', models.BooleanField(default=True)),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innova.products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmaCovigilance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('Last_update_date', models.DateTimeField(auto_now=True)),
                ('Last_update_by', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Image', models.ImageField(upload_to=innova.models.upload_image)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTitlePharmaCovigilance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('Last_update_date', models.DateTimeField(auto_now=True)),
                ('Last_update_by', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Image', models.ImageField(upload_to=innova.models.upload_image)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('pharmaCovigilance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innova.pharmacovigilance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTitleProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('Last_update_date', models.DateTimeField(auto_now=True)),
                ('Last_update_by', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Image', models.ImageField(null=True, upload_to=innova.models.upload_image)),
                ('order_by', models.IntegerField()),
                ('active_flag', models.BooleanField(default=True)),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innova.products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
        migrations.AlterField(
            model_name='career',
            name='attachCV',
            field=models.FileField(upload_to=innova.models.upload_cv),
        ),
    ]
