# Generated by Django 4.2.4 on 2023-12-18 14:12

from django.db import migrations, models
import innova.models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0013_patientsarea_pharmacovigilance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitleproducts',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=innova.models.upload_image),
        ),
    ]
