# Generated by Django 4.2.4 on 2023-12-18 17:11

from django.db import migrations, models
import innova.models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0014_alter_subtitleproducts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsarea',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=innova.models.upload_image),
        ),
    ]
