# Generated by Django 4.2.4 on 2023-12-18 17:19

from django.db import migrations, models
import innova.models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0015_alter_patientsarea_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacovigilance',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=innova.models.upload_image),
        ),
        migrations.AlterField(
            model_name='pharmacovigilance',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacovigilance',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtitlepharmacovigilance',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=innova.models.upload_image),
        ),
        migrations.AlterField(
            model_name='subtitlepharmacovigilance',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subtitlepharmacovigilance',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
