# Generated by Django 4.2.4 on 2023-12-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0016_alter_pharmacovigilance_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitleproducts',
            old_name='Products',
            new_name='products',
        ),
    ]
