# Generated by Django 4.2.4 on 2023-12-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0017_rename_products_subtitleproducts_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitlepharmacovigilance',
            name='order_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
