# Generated by Django 4.2.4 on 2024-01-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0018_subtitlepharmacovigilance_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='order_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
