# Generated by Django 4.2.4 on 2024-02-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innova', '0019_companyinformation_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitlepharmacovigilance',
            name='language',
            field=models.CharField(choices=[('AR', 'Freshman'), ('EN', 'Sophomore')], default='AR', max_length=3),
            preserve_default=False,
        ),
    ]
