# Generated by Django 4.2.4 on 2023-10-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('Last_update_date', models.DateTimeField(auto_now=True)),
                ('Last_update_by', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('child_list_flag', models.BooleanField(default=False)),
                ('order_by', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.navbar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
