# Generated by Django 4.2.4 on 2023-10-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_navbar_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='slug',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='navbar',
            name='folder_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.folderurl'),
        ),
    ]
