# Generated by Django 4.2.4 on 2023-10-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_folderurl_rename_slug_navbar_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderurl',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
