# Generated by Django 4.2.4 on 2023-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_folderurl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
    ]
