# Generated by Django 4.2.4 on 2023-10-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_navbar_active_flag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='navbar',
            unique_together={('parent', 'order_by')},
        ),
    ]
