# Generated by Django 4.2.4 on 2023-10-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_navbar_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='folder_url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.folderurl'),
        ),
    ]
